pipeline {

    agent any

    triggers {

        // Run every day at 6:00 PM
        cron('0 18 * * *')

        // Run whenever code is pushed to GitHub
        githubPush()
    }

    stages {

        stage('Install Dependencies') {
            steps {

                bat 'npm ci'

            }
        }


        stage('Run Playwright Tests') {
            steps {

                // Run tests sequentially because some tests depend on previous tests
                // Playwright logs will appear in Jenkins Console
                // JSON report will be generated by playwright.config.ts

                bat 'npx playwright test --workers=1'

            }
        }
    }


    post {

        always {

            script {

                def reportFile = 'playwright-report.json'

                def total = 0
                def passed = 0
                def failed = 0
                def skipped = 0

                def failedTests = []


                // Check whether JSON report exists

                if (fileExists(reportFile)) {

                    def reportResult = powershell(
                        returnStdout: true,

                        script: """
                            \$reportFile = '${reportFile}'

                            \$report = Get-Content \$reportFile -Raw | ConvertFrom-Json

                            \$total = 0
                            \$passed = 0
                            \$failed = 0
                            \$skipped = 0
                            \$flaky = 0


                            if (\$report.stats) {

                                \$passed = [int]\$report.stats.expected

                                \$failed = [int]\$report.stats.unexpected

                                \$skipped = [int]\$report.stats.skipped

                                \$flaky = [int]\$report.stats.flaky

                                \$total = \$passed + \$failed + \$skipped + \$flaky
                            }


                            Write-Output "TOTAL=\$total"

                            Write-Output "PASSED=\$passed"

                            Write-Output "FAILED=\$failed"

                            Write-Output "SKIPPED=\$skipped"


                            Write-Output "FAILED_TESTS_START"


                            function Get-FailedTests(\$suites) {

                                foreach (\$suite in \$suites) {

                                    foreach (\$spec in \$suite.specs) {

                                        foreach (\$test in \$spec.tests) {

                                            if (\$test.status -eq "unexpected") {

                                                Write-Output "\$(\$suite.title) - \$(\$spec.title)"

                                            }
                                        }
                                    }


                                    if (\$suite.suites) {

                                        Get-FailedTests \$suite.suites

                                    }
                                }
                            }


                            Get-FailedTests \$report.suites


                            Write-Output "FAILED_TESTS_END"
                        """
                    ).trim()


                    def readingFailedTests = false


                    reportResult.split("\\r?\\n").each { line ->


                        if (line.startsWith("TOTAL=")) {

                            total = line.substring(6).toInteger()

                        }


                        else if (line.startsWith("PASSED=")) {

                            passed = line.substring(7).toInteger()

                        }


                        else if (line.startsWith("FAILED=")) {

                            failed = line.substring(7).toInteger()

                        }


                        else if (line.startsWith("SKIPPED=")) {

                            skipped = line.substring(8).toInteger()

                        }


                        else if (line == "FAILED_TESTS_START") {

                            readingFailedTests = true

                        }


                        else if (line == "FAILED_TESTS_END") {

                            readingFailedTests = false

                        }


                        else if (readingFailedTests && line.trim()) {

                            failedTests.add(line.trim())

                        }
                    }

                }


                // If JSON report was not generated

                else {

                    echo "WARNING: playwright-report.json was not generated."

                    echo "Playwright execution may have failed before generating the report."

                }


                // Format failed tests

                def failedTestText = "No failed tests."


                if (failedTests.size() > 0) {

                    def counter = 1

                    def failedTestLines = []


                    failedTests.each { testName ->

                        failedTestLines.add(
                            "${counter}. ${testName}"
                        )

                        counter++

                    }


                    failedTestText = failedTestLines.join("\n")
                }


                // Send email

                emailext(

                    subject: "Playwright Test Report - Build #${BUILD_NUMBER} - ${currentBuild.currentResult}",


                    body: """
================================================
       PLAYWRIGHT AUTOMATION TEST REPORT
================================================

Build: #${BUILD_NUMBER}
Environment: QA
Browser: Chromium
Workers: 1

TEST SUMMARY
-----------------------------------------------
Total Tests       : ${total}
Passed            : ${passed}
Failed            : ${failed}
Skipped           : ${skipped}

FAILED TESTS
-----------------------------------------------
${failedTestText}

BUILD INFORMATION
-----------------------------------------------
Job               : ${JOB_NAME}
Build URL         : ${BUILD_URL}
Git Commit        : ${GIT_COMMIT ?: 'N/A'}
Branch            : ${GIT_BRANCH ?: 'main'}

================================================
""",

                    to: 'neelgaganat97@gmail.com'
                )
            }
        }
    }
}
